version: 2.1

description: |
  mojaloop/pr-tools is a CircleCI orb for convenience functions and utilities in Mojaloop CI/CD pipelines

executors:
  default:
    working_directory: /home/circleci/project
    docker:
      - image: node:12.16.1-alpine
      
jobs:
  pr-title-check:
    executor: default
    parameters:
      ci-config-branch:
        description: The branch of mojaloop/ci-config to bootstrap from
        default: master
        type: string
    steps:
      - setup-and-run-pr-title-check:
          ci-config-branch: << parameters.ci-config-branch >>

commands:
  setup-and-run-pr-title-check:
    description: Check the title of a Github pull request
    parameters:
      ci-config-branch:
        type: string
    steps:
      - run:
          name: Install general dependencies
          command: |
            apk --no-cache add git ca-certificates curl openssh-client
            apk add --no-cache -t build-dependencies make gcc g++ python libtool autoconf automake jq
      # Orbs don't let you package anything more than basic shell scripts
      # so we bootstrap this orb by checking out the code in the repo
      # TODO: checkout based on deterministic git tag
      - run:
          name: checkout ci-config repo
          command: |
            git clone -b << parameters.ci-config-branch >> https://github.com/mojaloop/ci-config.git
            cd ci-config/pr-tools && npm install
      - run:
          name: Check the PR title
          command: |
            echo "env CIRCLE_PULL_REQUESTS: ${CIRCLE_PULL_REQUESTS}"
            echo "env CIRCLE_PULL_REQUEST: ${CIRCLE_PULL_REQUEST}"
            cd ci-config/pr-tools &&  npm run pr-title

